export const bullionProducts = [
  {
    Item: 10001,
    id: "1ozGB",
    name: "1 oz Gold Bar | LBMA Approved",
    metal: "Gold",
    weight: 1,
    premium: 50,
  },
  {
    Item: 10002,
    id: "10ozGB",
    name: "10 oz Gold Bar | LBMA Approved",
    metal: "Gold",
    weight: 10,
    premium: 35,
  },
  {
    Item: 10003,
    id: "1KGGB",
    name: "1 Kilo Gold Bar | LBMA Approved",
    metal: "Gold",
    weight: 32.15,
    premium: 20,
  },
  {
    Item: 10004,
    id: "1GramGB",
    name: "1 Gram Gold Bar | LBMA Approved",
    metal: "Gold",
    weight: 0.03215,
    premium: 450,
  },
  {
    Item: 10005,
    id: "5GramGB",
    name: "5 Gram Gold Bar | LBMA Approved",
    metal: "Gold",
    weight: 0.16075,
    premium: 350,
  },
  {
    Item: 10006,
    id: "10GramGB",
    name: "10 Gram Gold Bar | LBMA Approved",
    metal: "Gold",
    weight: 0.3215,
    premium: 150,
  },
  {
    Item: 10007,
    id: "20GramGB",
    name: "20 Gram Gold Bar | LBMA Approved",
    metal: "Gold",
    weight: 0.642,
    premium: 100,
  },
  {
    Item: 10008,
    id: "50GramGB",
    name: "50 Gram Gold Bar | LBMA Approved",
    metal: "Gold",
    weight: 1.6075,
    premium: 50,
  },
  {
    Item: 10009,
    id: "100GramGB",
    name: "100 Gram Gold Bar | LBMA Approved",
    metal: "Gold",
    weight: 3.215,
    premium: 40,
  },
  {
    Item: 10010,
    id: "1ozGML",
    name: "1 oz Maple Leaf Gold Coin | RCM",
    metal: "Gold",
    weight: 1,
    premium: 90.0,
  },
  {
    Item: 10011,
    id: "1ozAGE",
    name: "1 oz American Eagle Gold Coin | US Mint",
    metal: "Gold",
    weight: 1,
    premium: 125.0,
  },
  {
    Item: 10012,
    id: "1ozAGB",
    name: "1 oz American Buffalo Gold Coin | US Mint ",
    metal: "Gold",
    weight: 1,
    premium: 125.0,
  },
  {
    Item: 10013,
    id: "1ozSR",
    name: "1 oz Silver Round | New, Various Mints",
    metal: "Silver",
    weight: 1,
    premium: 1,
  },
  {
    Item: 10014,
    id: "TubeSR",
    name: "Tube of Silver Rounds | New, Various Mints",
    metal: "Silver",
    weight: 20,
    premium: 0.85,
  },
  {
    Item: 10015,
    id: "BoxSR",
    name: "Monster Box of Silver Rounds | New, Various Mints",
    metal: "Silver",
    weight: 500,
    premium: 0.75,
  },
  {
    Item: 10016,
    id: "1ozSB",
    name: "1 oz Silver Bar | New, Various Mints",
    metal: "Silver",
    weight: 1,
    premium: 1.25,
  },
  {
    Item: 10017,
    id: "5ozSB",
    name: "5 oz Silver Bar | New, Various Mints",
    metal: "Silver",
    weight: 5,
    premium: 1,
  },
  {
    Item: 10018,
    id: "10ozSB",
    name: "10 oz Silver Bar | New, Various Mints",
    metal: "Silver",
    weight: 10,
    premium: 0.85,
  },
  {
    Item: 10019,
    id: "1KGSB",
    name: "1 Kilo Silver Bar | New, Various Mints",
    metal: "Silver",
    weight: 32.15,
    premium: 0.75,
  },
  {
    Item: 10020,
    id: "100ozSB",
    name: "100 oz Silver Bar | New, Various Mints",
    metal: "Silver",
    weight: 100,
    premium: 0.75,
  },
  {
    Item: 10021,
    id: "1ozSML",
    name: "1 oz Maple Leaf Silver Coin | New, RCM",
    metal: "Silver",
    weight: 1,
    premium: 2.75,
  },
  {
    Item: 10022,
    id: "1ozASE",
    name: "1 oz American Silver Coin | New, US Mint",
    metal: "Silver",
    weight: 1,
    premium: 4.5,
  },
  {
    Item: 10023,
    id: "TubeSML",
    name: "Tube of Maple Leaf Silver Coins | New, RCM",
    metal: "Silver",
    weight: 25,
    premium: 2.5,
  },
  {
    Item: 10024,
    id: "TubeASE",
    name: "Tube of American Eagle Silver Coins | New, US Mint",
    metal: "Silver",
    weight: 20,
    premium: 4.35,
  },
  {
    Item: 10025,
    id: "BoxSML",
    name: "Monster Box of Maple Leaf Silver Coins | New, RCM",
    metal: "Silver",
    weight: 500,
    premium: 2.35,
  },
  {
    Item: 10026,
    id: "BoxASE",
    name: "Monster Box of American Eagle Silver Coins | New, US Mint",
    metal: "Silver",
    weight: 500,
    premium: 4.15,
  },
  {
    Item: 10027,
    id: "10ozRCM",
    name: "10 oz Silver Bar | New, RCM",
    metal: "Silver",
    weight: 10,
    premium: 2.5,
  },
  {
    Item: 10028,
    id: "1KGRCM",
    name: "1 Kilo Silver Bar | New, RCM",
    metal: "Silver",
    weight: 32.15,
    premium: 1.25,
  },
  {
    Item: 10029,
    id: "100ozRCM",
    name: "100 oz Silver Bar | New, RCM",
    metal: "Silver",
    weight: 100,
    premium: 1.25,
  },
];

// Console log showing product array has imported
console.log("Product array imported...");
