export const bullionProducts = [
  {
    Item: 10001,
    id: "1ozGB",
    name: "1 oz Gold Bar | LBMA Approved",
    metal: "Gold",
    weight: 1,
    premium: 50,
  },
  {
    Item: 10002,
    id: "10ozGB",
    name: "10 oz Gold Bar | LBMA Approved",
    metal: "Gold",
    weight: 10,
    premium: 35,
  },
  {
    Item: 10003,
    id: "1KGGB",
    name: "1 Kilo Gold Bar | LBMA Approved",
    metal: "Gold",
    weight: 32.15,
    premium: 20,
  },
  {
    Item: 10004,
    id: "1GramGB",
    name: "1 Gram Gold Bar | LBMA Approved",
    metal: "Gold",
    weight: 0.03215,
    premium: 450,
  },
  {
    Item: 10005,
    id: "5GramGB",
    name: "5 Gram Gold Bar | LBMA Approved",
    metal: "Gold",
    weight: 0.16075,
    premium: 350,
  },
  {
    Item: 10006,
    id: "10GramGB",
    name: "10 Gram Gold Bar | LBMA Approved",
    metal: "Gold",
    weight: 0.3215,
    premium: 150,
  },
  {
    Item: 10007,
    id: "20GramGB",
    name: "20 Gram Gold Bar | LBMA Approved",
    metal: "Gold",
    weight: 0.642,
    premium: 100,
  },
  {
    Item: 10008,
    id: "50GramGB",
    name: "50 Gram Gold Bar | LBMA Approved",
    metal: "Gold",
    weight: 1.6075,
    premium: 50,
  },
  {
    Item: 10009,
    id: "100GramGB",
    name: "100 Gram Gold Bar | LBMA Approved",
    metal: "Gold",
    weight: 3.215,
    premium: 40,
  },
  {
    Item: 10010,
    id: "1ozGML",
    name: "1 oz Maple Leaf Gold Coin | RCM",
    metal: "Gold",
    weight: 1,
    premium: 90.00,
  },
  {
    Item: 10011,
    id: "1ozAGE",
    name: "1 oz American Eagle Gold Coin | US Mint",
    metal: "Gold",
    weight: 1,
    premium: 125.00,
  },
  {
    Item: 10012,
    id: "1ozAGB",
    name: "1 oz American Buffalo Gold Coin | US Mint ",
    metal: "Gold",
    weight: 1,
    premium: 125.00,
  },
];

// Console log showing product array has imported
console.log("Product array imported...");
